implemented the sort feature in comments by time
tegonhq/tegon pull request #336
Opened 2024-12-11 04:38 UTC by Dhruv218

2024-12-14 04:57 UTC, harshithmullapudi requested changes

2024-12-14 04:57 UTC, harshithmullapudi commented
Also can you run `pnpm lint` in the root folder

2024-12-14 09:36 UTC, Dhruv218 commented on apps/webapp/src/modules/issues/single-issue/left-side/activity/comments-activity/comments-activity.tsx
> +      {commentOrder<1 && <IssueComment />}
should i use condition  
commentOrder === -1 || commentOrder ===0

2024-12-17 06:07 UTC, harshithmullapudi approved these changes

2024-12-17 06:07 UTC, merged